export interface IOrder {
    id: number,
    id_address_delivery?: string,
    id_address_invoice?: string,
    id_cart?: string,
    id_currency?: string,
    id_lang?: string,
    id_customer?: string,
    id_carrier?: string,
    current_state?: string,
    module?: string,
    invoice_number?: string,
    invoice_date?: Date | string,
    delivery_number?: string,
    delivery_date?: Date | string,
    valid?: string,
    date_add?: Date | string,
    date_upd?: Date | string,
    shipping_number?: string,
    id_shop_group?: string,
    id_shop?: string,
    secure_key?: string,
    payment?: string,
    recyclable?: string,
    gift?: string,
    gift_message?: string,
    mobile_theme?: string,
    total_discounts?: number | string,
    total_discounts_tax_incl?: number | string,
    total_discounts_tax_excl?: number | string,
    total_paid?: number | string,
    total_paid_tax_incl?: number | string,
    total_paid_tax_excl?: number | string,
    total_paid_real?: number | string,
    total_products?: number | string,
    total_products_wt?: number | string,
    total_shipping?: number | string,
    total_shipping_tax_incl?: number | string,
    total_shipping_tax_excl?: number | string,
    carrier_tax_rate?: number | string,
    total_wrapping?: number | string,
    round_mode: number | string,
    round_type: number | string,
    conversion_rate: number | string,
    reference: number | string,
    associations: { [key: string]: IOrderItem[] },
}

export interface IOrderItem {
    id: number,
    product_id: number | string,
    product_attribute_id: string | number,
    product_quantity: string | number,
    product_name: string,
    product_reference: string,
    product_ean13: string,
    product_upc: string,
    product_price: number | string,
    unit_price_tax_incl: number | string,
    unit_price_tax_excl: number | string,
}

export interface IOrderState {
    id: number,
    unremovable?: number | string,
    delivery?: number | string,
    hidden?: number | string,
    send_email?: number | string,
    module_name?: string,
    invoice?: number | string,
    color?: string,
    logable?: number | string,
    shipped?: number | string,
    paid?: number | string,
    pdf_delivery?: number | string,
    pdf_invoice?: number | string,
    deleted?: number | string,
    name: string,
    template?: string,
}