export const LOCAL_EN = {
    'My Payment Methods': 'Mis Métodos de Pago',
    'Terms and Conditions': 'Términos y condiciones',
    'Privacy Policy': 'Política de Privacidad',
    'Back': 'Atras',
    'Featured': 'Promocionado',
    'Search': 'Buscar',
    'Categories': 'Categorías',
    'Cart': 'Carrito',
    'Account': 'Cuenta',
    'Shopping Cart': 'Carrito de compras',
    'Add to Cart': 'Agregar al Carrito',
    'All': 'Todo',
    'Search - e.g \"Dress\"': 'Buscar ej: \"Cebollas\"',
    'No item in cart': 'No hay items en el carrito',
    'Checkout': 'Realizar Pedido',
    'Reference': 'Referencia',
    'Condition': 'Condición',
    'More Info': 'Más Info',
    'Features': 'Características',
    'Accessories': 'Accessorios',
    'Edit': 'Editar',
    'Delete': 'Borrar',
    'Close': 'Cerrar',
    'Total': 'Total',
    'Tax': 'Impuestos',
    'Create an account': 'Crear Cuenta',
    'Sign in': 'Iniciar Sesión',
    'Sign out': 'Cerrar sesión',
    'My Account': 'Mi Cuenta',
    'Order history and details': 'Mis pedidos',
    'My addresses': 'Mis direcciones',
    'My personal information': 'Información personal',
    'Settings': 'Configuraciones',
    'Change language': 'Cambiar el idioma',
    'Select languages': 'Seleccionar el idioma',
    'First name': 'Nombres',
    'Last name': 'Apellidos',
    'E-mail': 'E-mail',
    'E-mail address': 'E-mail',
    'Date of Birth': 'Fecha de Nacimiento',
    'Password': 'Contraseña',
    'Current Password': 'Contraseña Actual',
    'New Password': 'Nueva Contraseña',
    'Repeat Password': 'Repetir Contraseña',
    'Confirmation': 'Confirmación',
    'Gender': 'Género',
    'Please select gender': 'Por favor seleccione el género',
    'Male': 'Hombre ',
    'Female': 'Mujer',
    'No address found': 'No tiene direcciones',
    'Company': 'Compañia',
    'Address': 'Dirección',
    'Address (Line 2)': 'Dirección (Secundaria)',
    'City': 'Ciudad',
    'State': 'Estado/Provincia',
    'Zip/Postal Code': 'Código postal',
    'Country': 'País',
    'Home phone': 'Teléfono convencional',
    'Mobile phone': 'Número Celular',
    'Additional information': 'Información Adicional',
    'Additional information hint': 'Color de casa o edificio, número de pisos, etc.',
    'Please assign an address title for future reference.': 'Alias o apodo de esta dirección',
    'Please assign an address title for future reference. hint': 'Ej: Casa, Edificio de trabajo, etc.',
    'Register': 'Registrar',
    'Save': 'Guardar',
    'Sign up for our newsletter!': 'Registrate para recibir novedades',
    'Receive special offers!': 'Recibe ofertas especiales',
    'No Order History': 'No tiene pedidos registrados',
    'No Order in Progress History': 'No tiene Pedidos en progreso',
    'Order history': 'Historial de pedidos',
    'Order reference': 'referencia de pedido',
    'Date': 'Fecha',
    'Total price': 'Total',
    'Payment': 'Pago',
    'Status': 'Estado',
    'Change Password': 'Cambiar Contraseña',
    'Required Field Error': 'Este campo es requerido',
    'Password Length Error': 'La contraseña debe tener 8 o más caracteres',
    'Confirm Password Error': 'No coincide con la contraseña nueva',
    'Select State': 'Seleccione una provincia',
    'Select City': 'Seleccione una ciudad',
    'Past Orders': 'Pedidos Anteriores',
    'In Progress Orders': 'Pedidos en progreso'
}

export const LOCAL_DE = {
    'Back': 'Zurück',
    'Featured': 'Vorgestellte',
    'Search': 'Suche',
    'Categories': 'Kategorien',
    'Cart': 'Warenkorb',
    'Account': 'Konto',
    'Shopping Cart': 'Warenkorb',
    'Add to Cart': 'In den Warenkorb',
    'All': 'Alles',
    'Search - e.g \"Dress\"': 'Suche - z.B. \"Kleid\"',
    'No item in cart': 'Leerer Warenkorb',
    'Checkout': 'Zur Kasse',
    'Reference': 'Artikel-Nr',
    'Condition': 'Zustand',
    'More Info': 'Mehr Infos',
    'Features': 'Eigenschaften',
    'Accessories': 'Zubehör',
    'Edit': 'Bearbeiten',
    'Delete': 'Löschen',
    'Close': 'Schließen',
    'Total': 'Gesamt',
    'Tax': 'MwSt.',
    'Create an account': 'Erstellen Sie ein Konto',
    'Sign in': 'Anmelden',
    'Sign out': 'Abmelden',
    'My Account': 'Ihr Kundenbereich',
    'Order history and details': 'Verlauf und Details Ihrer Bestellungen',
    'My addresses': 'Ihre Adressen',
    'My personal information': 'Ihre persönlichen Daten',
    'Settings': 'Einstellungen',
    'Change language': 'Sprache ändern',
    'Select languages': 'Sprachen auswählen',
    'First name': 'Vorname',
    'Last name': 'Name',
    'E-mail': 'E-mail',
    'E-mail address': 'E-Mail-Adresse',
    'Date of Birth': 'Geburtsdatum',
    'Password': 'Passwort',
    'Current Password': 'Aktuelles Passwort',
    'New Password': 'Neues Passwort',
    'Repeat Password': 'Passwort wiederholen',
    'Confirmation': 'Bestätigung',
    'Gender': 'Geschlecht',
    'Please select gender': 'Bitte wähle ein Geschlecht',
    'Male': 'Männlich ',
    'Female': 'Weiblich',
    'No address found': 'Keine Adresse',
    'Company': 'Firma',
    'Address': 'Adresse',
    'Address (Line 2)': 'Adresszusatz',
    'City': 'Stadt',
    'State': 'Bundesland',
    'Zip/Postal Code': 'PLZ',
    'Country': 'Land',
    'Home phone': 'Festnetznummer',
    'Mobile phone': 'Mobilfunknummer',
    'Additional information': 'Ergänzende Angaben',
    'Please assign an address title for future reference.': 'Geben Sie eine Kurzbezeichnung für diese Adresse ein, um sie künftig leichter zu finden',
    'Register': 'Registrieren',
    'Save': 'Speichern',
    'Sign up for our newsletter!': 'Abonnieren Sie unseren Newsletter!',
    'Receive special offers!': 'Erhalten Sie Sonderangebote!',
    'No order history': 'Keine Bestellverlauf',
    'Order history': 'Bestellverlauf',
    'Order reference': 'Bestell-Nr.',
    'Date': 'Datum',
    'Total price': 'Gesamtpreis',
    'Payment': 'Zahlungsart',
    'Status': 'Status'
}